const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
async function page(name,demo=true){const html=fs.readFileSync(name+'/index.html','utf8');const dom=new JSDOM(html,{url:'https://www.edendrive.fr/'+name+'/'+(demo?'?demo=1':''),runScripts:'outside-only'});const w=dom.window;w.confirm=()=>true;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async()=>({ok:true,json:async()=>({ready:false,payment:false})});w.eval(fs.readFileSync('assets/eden/app.js','utf8')+';window.testParisISO=parisISO;window.parisISO=parisISO;window.money=money;window.api=api;');await new Promise(r=>setImmediate(r));return dom;}
test('Driver demo displays, filters and confirms a request',async()=>{const dom=await page('espace-chauffeur'),w=dom.window,d=w.document;assert.equal(d.querySelectorAll('.ride').length,3);d.querySelector('.ride').click();assert(d.getElementById('rideDialog').open);d.getElementById('amount').value='57.50';d.getElementById('confirmForm').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.match(d.getElementById('rideBody').textContent,/Confirmée/);assert.match(d.getElementById('rideBody').textContent,/57,50/);d.querySelector('[data-filter="requested"]').click();assert.equal(d.querySelectorAll('.ride').length,0);dom.window.close();});
test('Customer demo records request without server or payment',async()=>{const dom=await page('reservation-eden'),w=dom.window,d=w.document;let calls=0;w.fetch=()=>{calls++;throw Error('No demo network');};d.querySelector('[name="consent"]').checked=true;d.getElementById('bookingForm').dispatchEvent(new w.SubmitEvent('submit',{cancelable:true,submitter:d.querySelector('button[type="submit"]')}));await new Promise(r=>setImmediate(r));assert.equal(calls,0);assert.equal(d.getElementById('bookingResult').hidden,false);assert.match(d.getElementById('bookingResult').textContent,/À confirmer/);assert.equal(d.getElementById('pay'),null);dom.window.close();});
test('Unconfigured customer form cannot submit real bookings',async()=>{const dom=await page('reservation-eden',false);assert(dom.window.document.getElementById('bookingFields').disabled);assert.match(dom.window.document.getElementById('message').textContent,/préparation/);dom.window.close();});
test('Paris local date conversion accounts for winter, summer and DST gap',async()=>{const dom=await page('reservation-eden');const w=dom.window;assert.equal(w.eval("window.testParisISO('2027-01-20','12:00')"),'2027-01-20T11:00:00.000Z');assert.equal(w.eval("window.testParisISO('2027-07-20','12:00')"),'2027-07-20T10:00:00.000Z');assert.throws(()=>w.eval("window.testParisISO('2027-03-28','02:30')"),/n’existe pas/);dom.window.close();});
test('Quote form displays road price, invalidates edits and keeps manual fallback available',async()=>{
 const dom=await page('reservation-eden',false),w=dom.window,d=w.document;
 d.getElementById('bookingFields').disabled=false;
 w.fetch=async()=>({ok:true,json:async()=>({amount:4879,distanceMeters:28700,durationSeconds:1620,token:'signed'})});
 w.eval(fs.readFileSync('assets/eden/quote.js','utf8'));
 assert(d.getElementById('customerFields').disabled);
 d.getElementById('pickup').value='Aéroport Marseille Provence';d.getElementById('dropoff').value='Gare Saint Charles Marseille';
 d.getElementById('calculatePrice').click();await new Promise(r=>setImmediate(r));
 assert.match(d.getElementById('quotePrice').textContent,/48,79/);assert.match(d.getElementById('quoteStatus').textContent,/28,7 km/);assert(!d.getElementById('customerFields').disabled);
 d.getElementById('pickup').dispatchEvent(new w.Event('input'));assert.equal(w.edenQuote,null);assert(d.getElementById('customerFields').disabled);
 d.getElementById('manualRequest').click();assert(w.edenManual);assert(!d.getElementById('customerFields').disabled);
 dom.window.close();
});
