const { randomUUID }=require('node:crypto');const {token,hash}=require('./security.cjs');
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function txt(x,max=200){if(typeof x!=='string')return '';return x.trim().replace(/[\x00-\x1f]/g,' ').slice(0,max);}
function validate(d,now=Date.now()){
 const b={name:txt(d.name,100),email:txt(d.email,150),phone:txt(d.phone,30),pickup:txt(d.pickup,300),dropoff:txt(d.dropoff,300),pickupAt:txt(d.pickupAt,50),service:txt(d.service,40),flight:txt(d.flight,40),sign:txt(d.sign,80),notes:txt(d.notes,600),billingAddress:txt(d.billingAddress,300),company:txt(d.company,150),siren:txt(d.siren,14),passengers:Number(d.passengers),bags:Number(d.bags)};
 if(!b.name||!/^\S+@\S+\.\S+$/.test(b.email)||!/^[+\d ()-]{8,30}$/.test(b.phone))fail('Vérifiez le nom, l’email et le téléphone.');
 if(b.pickup.length<5||b.dropoff.length<5||b.pickup===b.dropoff)fail('Indiquez deux adresses différentes et complètes.');
 const t=Date.parse(b.pickupAt);if(!/Z$|[+-]\d\d:\d\d$/.test(b.pickupAt)||!Number.isFinite(t)||t<now+15*60000||t>now+366*86400000)fail('Choisissez une date entre 15 minutes et un an à partir de maintenant.');
 b.pickupAt=new Date(t).toISOString();
 if(!['airport','station','city','hourly'].includes(b.service)||!Number.isInteger(b.passengers)||b.passengers<1||b.passengers>4||!Number.isInteger(b.bags)||b.bags<0||b.bags>4)fail('Vérifiez le service, les passagers et les bagages.');
 if(d.consent!==true)fail('Veuillez accepter le traitement de votre demande.');return b;
}
function profile(env=process.env){try{return JSON.parse(env.EDEN_COMPANY_JSON||'{}');}catch{return {};}}
function legalReady(p){return !!(p.legalName&&p.address&&/^\d{14}$/.test(p.siret||'')&&p.phone&&p.email&&p.driverName&&p.driverCard&&p.vehicle&&p.plate&&['exempt','taxable'].includes(p.vatMode)&&(p.vatMode==='exempt'||(Number.isFinite(p.vatRate)&&p.vatRate>=0&&p.vatRate<=25&&p.vatNumber)));}
function amounts(cents,p){const ht=p.vatMode==='exempt'?cents:Math.round(cents/(1+p.vatRate/100));return {ttc:cents,ht,tax:cents-ht,rate:p.vatMode==='exempt'?0:p.vatRate};}
function paymentMatches(check,b,merchant){return check.id===b.checkout_id&&check.status==='PAID'&&check.currency==='EUR'&&Math.round(Number(check.amount)*100)===b.amount&&check.checkout_reference===b.id&&check.merchant_code===merchant;}
function createService(db){return {
 async create(input){const data=validate(input);const id=randomUUID(),access=token(),ref='ED-'+id.slice(0,8).toUpperCase();await db.query('INSERT INTO eden_bookings(id,ref,token_hash,data) VALUES($1,$2,$3,$4)',[id,ref,hash(access),JSON.stringify(data)]);return {id,ref,token:access,status:'requested',data};},
 async createQuoted(input,q,access){const data=validate(input);data.pricing={distanceKm:q.distanceMeters/1000,rateCents:170,durationSeconds:q.durationSeconds};const ref='ED-'+q.id.slice(0,8).toUpperCase();return db.transaction(async c=>{
 await c.query("SELECT pg_advisory_xact_lock(170170)");
 const existing=(await c.query('SELECT * FROM eden_bookings WHERE id=$1',[q.id])).rows[0];if(existing)return {...publicBooking(existing),token:access};
 const occupied=await c.query("SELECT 1 FROM eden_bookings WHERE status='confirmed' AND (data->>'pickupAt')::timestamptz < $2::timestamptz AND (data->>'pickupAt')::timestamptz + make_interval(secs => COALESCE((data->'pricing'->>'durationSeconds')::int,3600)+1800) > $1::timestamptz",[data.pickupAt,new Date(Date.parse(data.pickupAt)+(q.durationSeconds+1800)*1000).toISOString()]);
 if(occupied.rows.length)fail('Ce créneau est déjà réservé. Choisissez un autre horaire ou appelez EdenDrive.',409);
 const result=await c.query("INSERT INTO eden_bookings(id,ref,token_hash,data,status,amount) VALUES($1,$2,$3,$4,'confirmed',$5) RETURNING *",[q.id,ref,hash(access),JSON.stringify(data),q.amount]);return {...publicBooking(result.rows[0]),token:access};});},
 async get(id,access,admin=false){if(!/^[0-9a-f-]{36}$/i.test(id||''))fail('Réservation introuvable.',404);const r=await db.query('SELECT * FROM eden_bookings WHERE id=$1'+(admin?'':' AND token_hash=$2'),admin?[id]:[id,hash(access||'')]);if(!r.rows[0])fail('Réservation introuvable.',404);return r.rows[0];},
 async list(){return (await db.query('SELECT * FROM eden_bookings ORDER BY created_at DESC LIMIT 200')).rows;},
 async change(id,action,input,p){return db.transaction(async c=>{const r=await c.query('SELECT * FROM eden_bookings WHERE id=$1 FOR UPDATE',[id]);const b=r.rows[0];if(!b)fail('Réservation introuvable.',404);
  if(action==='confirm'){if(b.status!=='requested')fail('Cette demande a déjà été traitée.',409);const km=input.distanceKm==null?null:Number(input.distanceKm);if(km!==null&&(!Number.isFinite(km)||km<0.1||km>5000))fail('Distance invalide.');const amount=km===null?Number(input.amount):Math.round(km*170);if(!Number.isInteger(amount)||amount<100||amount>1000000)fail('Prix invalide.');if(!legalReady(p))fail('Complétez les informations de l’entreprise avant de confirmer.',503);await c.query("UPDATE eden_bookings SET status='confirmed',amount=$2,updated_at=now() WHERE id=$1",[id,amount]);if(km!==null)await c.query("UPDATE eden_bookings SET data=jsonb_set(data,'{pricing}',$2::jsonb) WHERE id=$1",[id,JSON.stringify({distanceKm:km,rateCents:170})]);}
  else if(action==='complete'){if(b.status!=='confirmed')fail('Confirmez d’abord la course.',409);if(Date.parse(b.data.pickupAt)>Date.now())fail('La course ne peut pas être terminée avant sa prise en charge.');await c.query("UPDATE eden_bookings SET status='completed',updated_at=now() WHERE id=$1",[id]);}
  else if(action==='cancel'){if(b.paid||b.checkout_id||b.invoice_no||b.status==='completed')fail('Course payée, facturée ou paiement engagé : traitement manuel nécessaire.',409);await c.query("UPDATE eden_bookings SET status='cancelled',updated_at=now() WHERE id=$1",[id]);}
  else if(action==='paid'){if(!['confirmed','completed'].includes(b.status)||b.checkout_id)fail('Vérifiez le paiement SumUp pour cette course.',409);if(!['cash','card','transfer'].includes(input.method))fail('Choisissez le moyen de paiement.');await c.query('UPDATE eden_bookings SET paid=true,paid_at=now(),payment_method=$2,updated_at=now() WHERE id=$1',[id,input.method]);}
  else if(action==='assign'){if(b.invoice_no||['completed','cancelled'].includes(b.status))fail('Course clôturée.',409);const driver={name:txt(input.name,100),phone:txt(input.phone,30),card:txt(input.card,50),vehicle:txt(input.vehicle,80),plate:txt(input.plate,20)};if(Object.values(driver).some(x=>!x))fail('Complétez toutes les informations du chauffeur.');b.data.driver=driver;await c.query('UPDATE eden_bookings SET data=$2,updated_at=now() WHERE id=$1',[id,JSON.stringify(b.data)]);}
  else if(action==='invoice'){if(b.invoice_no)return b;if(b.status!=='completed'||!b.amount)fail('La facture définitive est émise après la course.',409);if(!legalReady(p)||!b.data.billingAddress)fail('Informations de facturation incomplètes.');if(b.data.company&&!p.latePaymentTerms)fail('Renseignez les conditions de retard pour les clients professionnels.');const nr=await c.query('UPDATE eden_invoice_counter SET value=value+1 WHERE id=1 RETURNING value');const number='ED-F-'+String(nr.rows[0].value).padStart(6,'0');const snapshot={number,issuedAt:new Date().toISOString(),company:p,booking:{ref:b.ref,data:b.data,amount:b.amount},totals:amounts(b.amount,p)};await c.query('UPDATE eden_bookings SET invoice_no=$2,invoice_snapshot=$3,updated_at=now() WHERE id=$1',[id,number,JSON.stringify(snapshot)]);}
  else fail('Action inconnue.');await c.query('INSERT INTO eden_events(booking_id,action) VALUES($1,$2)',[id,action]);return (await c.query('SELECT * FROM eden_bookings WHERE id=$1',[id])).rows[0];});}
 };}
function publicBooking(b){const {token_hash,...safe}=b;delete safe.checkout_id;delete safe.invoice_snapshot;return safe;}
module.exports={fail,validate,profile,legalReady,amounts,paymentMatches,createService,publicBooking};
