const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function emailContent(b,link,type='reservation',driver=false){
 const pending=b.status==='requested',invoice=type==='invoice';
 const paymentChoice=type.startsWith('payment-choice'),paymentReceived=type==='payment-received',onboard=['cash','onboard'].includes(b.data.paymentPreference);
 const title=driver?(paymentReceived?'Paiement reçu':paymentChoice?'Mode de paiement choisi':pending?'Nouvelle demande à confirmer':'Course confirmée'):paymentReceived?'Votre paiement a bien été reçu':paymentChoice?'Votre mode de paiement est enregistré':invoice?'Votre facture est disponible':pending?'Votre demande a bien été reçue':'Votre réservation est confirmée';
 const price=b.amount==null?'Tarif à confirmer':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(b.amount/100);
 const date=new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(b.data.pickupAt));
 const note=driver?('Client : '+b.data.name+' · '+b.data.phone+'. '+(b.paid?'Paiement reçu — '+(b.payment_method==='sumup'?'carte en ligne':b.payment_method||'règlement enregistré')+'.':onboard?'À encaisser en fin de course, en espèces ou par carte.':b.data.paymentPreference==='online'?'Carte en ligne choisie. Paiement pas encore reçu.':'Mode de paiement non choisi.')):paymentReceived?'Merci, votre trajet est réglé. Aucun autre paiement n’est demandé pour cette course.':paymentChoice?(onboard?'Vous avez choisi de payer en fin de course, en espèces ou par carte auprès du chauffeur. Rien à payer en ligne. Votre chauffeur est informé de ce choix.':'Vous avez choisi de payer par carte en ligne. Le paiement reste à effectuer. Votre chauffeur est informé de ce choix.'):invoice?'Retrouvez votre facture dans votre réservation.':pending?'Votre chauffeur vérifie sa disponibilité. Vous recevrez un email de confirmation. Rien à payer pour le moment.':b.paid?'Votre paiement a bien été reçu. Votre bon de réservation est disponible.':'Payez en ligne ou choisissez de régler à la fin de la course, en espèces ou par carte. Votre bon de réservation est disponible sur la même page.';
 const cta=driver?'Ouvrir mon espace chauffeur':paymentChoice&&onboard?'Voir ma réservation':invoice?'Télécharger ma facture':pending?'Suivre ma demande':b.paid?'Voir mon bon de réservation':'Voir ma réservation et payer';
 const text=`${title}\n\nBonjour ${driver?'Jonathan':b.data.name},\n${price}\n${date} (heure de Paris)\n${b.data.pickup}\n→ ${b.data.dropoff}\n\n${note}\n\n${cta} :\n${link}\n\nUne question ? 06 87 39 26 32\nEdenDrive · ${b.ref}`;
 const html=`<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;background:#faf7f0;font-family:Arial,sans-serif;color:#202822"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;margin:auto;background:#fffefa;border:1px solid #e4e3d9;border-radius:16px"><tr><td style="padding:32px 24px"><p style="letter-spacing:5px;color:#b28c3f;font-size:15px;margin:0 0 24px">EDEN DRIVE</p><h1 style="font-size:26px;line-height:1.3;margin:0 0 20px">${escape(title)}</h1><p>Bonjour ${escape(driver?'Jonathan':b.data.name)},</p><p style="font-size:40px;margin:20px 0;color:#202822;font-weight:bold">${escape(price)}</p><p style="font-size:16px;line-height:1.6"><strong>${escape(date)}</strong><br>Heure de Paris</p><div style="padding:18px;background:#faf7f0;border-radius:8px;font-size:16px;line-height:1.6"><strong>Départ</strong><br>${escape(b.data.pickup)}<br><br><strong>Arrivée</strong><br>${escape(b.data.dropoff)}</div><p style="line-height:1.6;font-size:16px;margin:24px 0">${escape(note)}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" bgcolor="#b28c3f" style="border-radius:8px"><a href="${escape(link)}" style="display:block;padding:20px 16px;color:#ffffff;font-size:18px;line-height:1.4;font-weight:bold;text-decoration:none">${escape(cta)} →</a></td></tr></table><p style="font-size:14px;line-height:1.6;margin-top:28px">Une question ? <a href="tel:+33687392632" style="color:#202822">06 87 39 26 32</a></p><p style="font-size:12px;color:#70776d">EdenDrive · ${escape(b.ref)}<br>Gardez ce lien personnel pour retrouver votre trajet.</p></td></tr></table></td></tr></table></body></html>`;
 return {title,subject:title+' · EdenDrive',cta,note,text,html};
}
module.exports={emailContent};
