const PDFDocument=require('pdfkit');
module.exports=function voucher(b,p){return new Promise((resolve,reject)=>{
 const d=new PDFDocument({size:'A4',margin:0,info:{Title:'Bon de réservation EdenDrive',CreationDate:new Date(b.created_at)}}),chunks=[];
 d.on('data',c=>chunks.push(c));d.on('end',()=>resolve(Buffer.concat(chunks)));d.on('error',reject);
 const W=595.28,H=841.89,L=56,R=539,width=483,gold='#c8a747',black='#191919',grey='#858585';let y=192;
 const date=s=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(s));
 const text=(s,x,top,size=9,color=black,opts={})=>d.fillColor(color).font('Helvetica').fontSize(size).text(String(s||''),x,top,{width:width,characterSpacing:0,...opts});
 function footer(){d.rect(0,H-66,W,66).fill(black);d.rect(0,H-66,W,3).fill(gold);text('E D E N  D R I V E',L,H-44,10,gold);text('SIRET '+p.siret,355,H-42,7,grey,{width:184,align:'right'});text(p.address+' · '+p.email+' · edendrive.fr',L,H-23,6.5,'#dddddd',{width});}
 function header(){d.rect(0,0,W,117).fill(black);d.rect(0,114,W,4).fill(gold);text('E D E N  D R I V E',L,35,22,gold);text('S E R V I C E  V T C  P R E M I U M  -  M A R S E I L L E',L,67,6.5,grey,{width:340});text(p.legalName+' · '+p.email+' · SIRET '+p.siret,L,86,6.5,'#eeeeee',{width});text('RÉFÉRENCE',365,42,6,grey,{width:174,align:'right'});text(b.ref,355,57,10,gold,{width:184,align:'right'});text('Émis le '+new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeZone:'Europe/Paris'}).format(new Date(b.created_at)),355,77,6.5,grey,{width:184,align:'right'});text('B O N  D E  R É S E R V A T I O N',L,148,12,black,{align:'center'});text('Chauffeur privé - Marseille & Provence',L,171,8,grey,{align:'center'});}
 function room(h){if(y+h>H-91){footer();d.addPage();header();y=205;}}
 function section(label){room(45);y+=14;text(label,L,y,8,gold,{characterSpacing:1.5});y+=15;d.moveTo(L,y).lineTo(R,y).strokeColor(gold).lineWidth(.7).stroke();y+=7;}
 let stripe=0;function row(label,value){if(!value)return;d.font('Helvetica').fontSize(9);const h=Math.max(24,d.heightOfString(String(value),{width:350})+14);room(h);if(stripe++%2===0)d.rect(L,y,width,h).fill('#f3f3f3');text(label,L+8,y+8,7,grey,{width:107,characterSpacing:.7});text(value,L+119,y+7,9,black,{width:width-129});y+=h;}
 header();section('CLIENT');row('NOM',b.data.name);row('CONTACT',b.data.phone+' · '+b.data.email);
 section('VOTRE TRAJET');stripe=0;row('DATE',date(b.data.pickupAt)+' (heure de Paris)');row('PRISE EN CHARGE',b.data.pickup);row('DESTINATION',b.data.dropoff);
 const driver=b.data.driver||{name:p.driverName,card:p.driverCard,phone:p.phone,vehicle:p.vehicle,plate:p.plate};row('VÉHICULE',driver.vehicle+' - '+driver.plate);row('CHAUFFEUR',driver.name+' · '+driver.phone);row('CARTE VTC',driver.card);row('PASSAGERS',b.data.passengers+' · '+b.data.bags+' bagage(s)');if(b.data.flight)row('VOL / TRAIN',b.data.flight);if(b.data.sign)row('PANCARTE',b.data.sign);if(b.data.notes)row('PRÉCISIONS',b.data.notes);
 room(155);y+=16;d.rect(L,y,width,51).fill(black);text(b.paid?'TOTAL RÉGLÉ':'TOTAL À RÉGLER',L+16,y+14,9,'#ffffff',{width:240,characterSpacing:1});text('Prix total du trajet',L+16,y+32,7,grey,{width:240});text((b.amount/100).toFixed(2).replace('.',',')+' € TTC',L+280,y+13,21,gold,{width:185,align:'right'});y+=68;
 const conditions=[b.paid?'Règlement enregistré le '+date(b.paid_at)+'.':b.data.paymentPreference==='cash'?'Paiement en espèces à la fin de la course.':'Paiement par carte en ligne ou en espèces à la fin de la course.',p.vatMode==='exempt'?'TVA non applicable, article 293 B du CGI.':'TVA : '+p.vatRate+' %.','Réservation enregistrée le '+date(b.created_at)+'.'];
 d.rect(L,y,width,76).fill('#f3f3f3');d.rect(L,y,3,76).fill(gold);text('INFORMATIONS',L+17,y+11,8,black,{characterSpacing:1});conditions.forEach((line,i)=>text('• '+line,L+17,y+29+i*13,7.5,black,{width:width-30}));y+=88;room(20);text('Merci de votre confiance - à bientôt à bord !',L,y,9,grey,{align:'center'});footer();d.end();
});};
